: "${MECHASHIP_UDEV_RULE:=98-mechaship-v26.06a.rules}"
: "${MECHASHIP_REPO_BRANCH:=jazzy-uipa}"
: "${MECHASHIP_BOARD:=rock-5a}"
: "${MECHASHIP_NETPLAN_FILE:=90-NM-370a22f3-2193-441b-9174-c1be89b425f2.yaml}"
